version: "3"

services:
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=password1234"
  app:
    build: .
    ports:
      - "3000:3000"
      - "8080:3000"
    environment:
      - "DATABASE_HOST=db"
      - "DATABASE_NAME=dbname"
      - "DATABASE_PORT=5432"
      - "DATABASE_USER=postgres"
      - "DATABASE_PASSWORD=password1234"
      - "DATABASE_ENCODING=utf8"
      - "RAILS_ENV=development"
    depends_on:
      - db
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - ".:/myapp"
